import  LinkedList from './LinkedList.js'
const linkedList = new LinkedList()
linkedList.push(15)
linkedList.push(10)
console.log(linkedList.insert(100,0))
console.log(linkedList.insert(20,10))
console.dir(linkedList)
// linkedList.removeAt(0)
// console.dir(linkedList)
console.dir(linkedList.getElementAt(2))
console.dir(linkedList.getElementAt(3))
console.log(linkedList.indexOf(100))
console.log(linkedList.indexOf(10))
console.log(linkedList.toString())